### ISSUE TITLE
副本分数控制逻辑未生效

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#12]
哈士奇副本第2层，配置的要求dps = 2，带了哈士奇1级进去打（配了dps = 1），结果还是按100%在算得分，应该按20%算得分。

**Comment by cqnature** [comment]
因为之前的逻辑没有理解清楚，使用的是英雄的dps和requireAttack做的比较，现在已修复成宠物副本除外的关卡使用英雄的dps，宠物副本使用宠物的dps。

**Comment by aoxu** [comment]
已验证。
