### ISSUE TITLE
无法上传记录，并且提示boss榜在结算

### ISSUE THREAD

**Issue by nerodragon** [aoxu/MiniMerry#123]
打完记录后，上传不了，有上传图标，点击之后提示不可提交成绩（文案是Boss榜结算后2小时~4小时内不可提交的文案）

**Comment by Kinderzhang** [comment]
手动重置数据会把 boss周的数据清空， 需要再次登录有游戏 或者 上传一次数据 然后就会更新 下一次就会可以上传
