### ISSUE TITLE
成就系统领取部分奖励，所有成就项会变为两个

### ISSUE THREAD

**Issue by nerodragon** [aoxu/MiniMerry#127]
1.成就系统，完成了飞越无限的成绩，点击领取奖励，所有的成就都变成了两个，再次领取了伟大冒险家之后又变回正常了。
2.用金币升级所有任务以后，成就界面显示错误，从不醉不归成就开始所有成就显示2个，但是完成一个成就以后就变成正常。

**Comment by aoxu** [comment]
已验证。
