### ISSUE TITLE
宇航员的僚机打会闪现的BOSS有时候会在BOSS闪现的时候，电到屏幕的左下角。

### ISSUE THREAD

**Issue by cqusyc** [aoxu/MiniMerry#148]

**Comment by cqnature** [comment]
宇航员的僚机是攻击boss的buff1点的，如果动画里buff1点的位置有问题，或者buff1骨骼点位置获取异常的话可能出这个问题，这个要先确定是哪个boss然后再排查。

**Comment by cqnature** [comment]
wego说忍者猫会出现，但是没有重现。
