### ISSUE TITLE
赌场的奖励全部领完以后还可以点击进入赌场按钮，点击后按钮消失没有其他反馈。

### ISSUE THREAD

**Issue by cqnature** [aoxu/MiniMerry#161]
有在测试页面点击一键全解锁宠物。

**Comment by Kinderzhang** [comment]
有可能是浮点数判断问题，100<= 999.99999 的问题 。 这里对数据向上取整

**Comment by Kinderzhang** [comment]
`-- 计算权重 获得随机
    local random = math.random(100)
    local probability = 0
    local nextProbability = 0
    local openData = nil
    for k,v in ipairs(itemList) do
        nextProbability = nextProbability + v.weight/allWeight * 100
        if random >= probability and random <= math.ceil(nextProbability) then
            openData = v
            break
        end
        probability = nextProbability
    end`

**Comment by Kinderzhang** [comment]
`-- 计算权重 获得随机
    local random = math.random(100)
    local probability = 0
    local nextProbability = 0
    local openData = nil
    for k,v in ipairs(itemList) do
        nextProbability = nextProbability + v.weight/allWeight * 100
        if random >= probability and random <= math.ceil(nextProbability) then
            openData = v
            break
        end
        probability = nextProbability
    end`

**Comment by Kinderzhang** [comment]
修改了以后 难以重现

**Comment by Kinderzhang** [comment]
的确可以出现， 把本轮的 宝石和金币获取了以后，  去把收集物全收集满就会出现这个异常。 现在修改了检查逻辑， 登录以及得到收集物的时候 会去检查赌场的开启时间

**Comment by aoxu** [comment]
已验证。
