### ISSUE TITLE
UI上的宠物宝箱可以点击查看描述

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#18]
![](http://ww1.sinaimg.cn/large/70dcc3a2gw1f9zox9oibpj21120kumyk.jpg)
如图，神秘指令的宝箱和商店的宝箱都可以点击，点击之后，都弹出点了i按钮的详细描述

**Comment by aoxu** [comment]
@nearth 的数值确定后，@aoxu 需要在描述文案里补充每种获得物分别得多少个。

**Comment by Kinderzhang** [comment]
已加入点击事件逻辑

**Comment by aoxu** [comment]
UI已验证，待修改文案。

**Comment by aoxu** [comment]
已修改文案并验证。
