### ISSUE TITLE
任务系统

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/MiniMerry#180]
1.最后一组任务，点击跳过任务按钮，金币扣了，任务没有完成。
2.最后一组循环的任务，组奖励从集合中随机抽取。
3.最后一组循环的任务，因为分数倍数已经不再上涨，玩家做任务只是为了领取奖励，任务标题下的任务组5可以去除，分数倍数也不显示。
4.战中的任务面板，子任务点击时的点击动画可以去除（现在未完成状态也可以点击，点击了没有提示，比较奇怪）

**Comment by Kinderzhang** [comment]
问题1 是配置配错了
问题2 需求没有要这样做
问题3 已修改
问题4 已修改
