### ISSUE TITLE
携带技能型宠物经过捕捉动画以后拾取宠物失败。

### ISSUE THREAD

**Issue by cqnature** [aoxu/MiniMerry#20]
技能型宠物携带到boss捕捉动画中后，再拾取其他宠物不会覆盖当前宠物。当前宠物消失后之前拾取的宠物才会再次触发。

**Comment by cqnature** [comment]
问题已修复，触发逻辑是连续拾取2个以上的有技能的宠物。
原来的逻辑有个漏洞，有技能的宠物在触发入场动画的过程中再拾取一个宠物的话，本来有技能宠物接着触发出场动画，但是因为技能没有被使用掉而判断不能出场。这里判断逻辑已修改。

**Comment by aoxu** [comment]
已验证。
