### ISSUE TITLE
蜗牛跟在英雄身后会一直出现动画卡顿

### ISSUE THREAD

**Issue by cqnature** [aoxu/MiniMerry#21]
这个是wego记录的问题，我review了代码，应该是在某些特殊的位置会出现跟随动画和移动动画不停的互相打断的逻辑。

**Comment by cqnature** [comment]
问题已修复，不停切换跟随和移动的逻辑应该只有在玩家小幅度移动的过程中会出现，每次宠物只需要移动一小段距离就会切到跟随动画了。现在的逻辑修改成移动动画和跟随动画结束后再去判断播放移动还是跟随动画，这样就不会互相打断。

**Comment by aoxu** [comment]
已验证。
