### ISSUE TITLE
有种流程下，主界面点宠物必崩～

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#26]
1.先初始化用户数据。
2.一键解锁所有宠物，一键解锁所有副本的所有层。
3.打金猪副本第3层，用5只默认宠物搭配（没改过），一进战斗立即点暂停退出，回到主界面。
4.在主界面点宠物图标，必崩，连线看是内存原因。

环境：iOS 10.1.1，iPad mini 3（刚手动重启过，没有后台程序，内存应该是很充足的）。

**Comment by cqusyc** [comment]
iPad下，进入宠物页面，内存直接涨30MB，这是导致崩溃的原因

**Comment by cqusyc** [comment]
iPad下，原来进入宠物页面有232MB内存，现在通过移除不必要加载的ui内存，已降低至178MB

**Comment by aoxu** [comment]
已验证，不崩了。
