### ISSUE TITLE
新手任务引导

### ISSUE THREAD

**Issue by Zimering** [aoxu/MiniMerry#275]
任务完成领取奖励，太硬，缺少key

**Comment by Zimering** [comment]
快来领取奖励吧，太硬了

**Comment by aoxu** [comment]
宠物收藏家系统解锁后，出现引导文案，有个错误写的是“升级物”，应该是“收集物”～

**Comment by Zimering** [comment]
击杀BOSS可以获得此道具（第一次解锁转盘） 应该是获得的启动宝石可以用来启动转盘

**Comment by Zimering** [comment]
任务组5的获得，打火机。 显示获得了收集物，积累收集物可以解锁新宠物-》应该是获得了打火机，打火机用于解锁新的英雄皮肤

**Comment by Zimering** [comment]
任务组5获得大爹鼠收集物，收集物名字没有，但是已经配了

**Comment by Zimering** [comment]
成就已完成，来领取奖励吧

**Comment by Zimering** [comment]
宠物收藏家页面，左边换收集物，特卖数量缺少中文文案

**Comment by Zimering** [comment]
升级你的英雄榜等级，（11组任务做完以后）应该是升级你的英雄等级

**Comment by Zimering** [comment]
11组任务2个进入league榜
