### ISSUE TITLE
第一次升级宠物的引导卡住了，点什么都没反应～

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#411]
feature-missionstage分支～
好像是我点得有点快，点了“宠物”按钮后从战后已经跳转到宠物养成界面了，但是引导没变，指向“宠物”按钮的箭头还在跳动，引导没往下一步走～

**Comment by Kinderzhang** [comment]
修改了 触发逻辑 需要再测试下看看

**Comment by aoxu** [comment]
测试了，狂点也不会触发～
