### ISSUE TITLE
看小电视的时候叉掉广告也能得可乐

### ISSUE THREAD

**Issue by nerodragon** [aoxu/MiniMerry#42]

**Comment by Kinderzhang** [comment]
问题找到了 因为AppLovin有时候会加载一个demo game 这种广告是可以给玩家在上面玩一个小型游戏 这边跟 @nearth 商量了这种类型广告 关闭也给奖励。因为这种广告是有个关闭按钮的，并没有时间限制的。

**Comment by aoxu** [comment]
已验证。
