### ISSUE TITLE
战后结束界面的任务目标计数，如果达成了目标，计数有时候是大于任务要求的～

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#434]
比如有时候看到2-8的目标是51/50，应该是50/50

**Comment by cqnature** [comment]
问题已修复。

**Comment by aoxu** [comment]
测试发现新的问题，失败时（没有达到任务目标）战后结束界面的任务计数为0～
举例，3-11关，目标是得分300分，实际战中得分是220/300，战后显示是0/300～

**Comment by aoxu** [comment]
目标计数溢出的问题确实修复了，已验证～

**Comment by cqnature** [comment]
没达成的情况下的问题已修复。

**Comment by aoxu** [comment]
已验证～
