### ISSUE TITLE
宠物副本里，英雄成长对宠物普攻+技能伤害有影响。

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#63]
宠物副本的定位是只考验宠物的成长，与英雄成长无关。
这个数值机制应该改为，固定取1号皮肤1级的攻击力，不管玩家在无尽模式选的是哪个皮肤，升了几级。

**Comment by Kinderzhang** [comment]
获取战斗数据的时候 区分宠物副本， 强制获取1号皮肤的1级技能属性。 已提交 @aoxu 验证

**Comment by aoxu** [comment]
已验证。
