### ISSUE TITLE
最高分图片需要支持微信分享～

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#79]

**Comment by Kinderzhang** [comment]
测试了下 跟Facebook 一样 如果有链接 会把图片给取消掉

**Comment by aoxu** [comment]
除了微信还要支持微博分享～

**Comment by aoxu** [comment]
截取的图片不要白边～

**Comment by Kinderzhang** [comment]
文案key:
SCAN TO DOWNLOAD FOR FREE 
BY
BEST BEAT TIME
MY SCORE!
BEAT
Share success
Share the failure

**Comment by aoxu** [comment]
已验证。
