### ISSUE TITLE
当副本进去的时候，没有获得。应该给个弹窗提示的

### ISSUE THREAD

**Issue by aoxu** [aoxu/MiniMerry#80]
弹窗提示一段文本，传达几个意思：
1.奖励次数的概念，而且已经消耗完了。
2.训练消耗0可乐，可以无限次训练。
3.没有获得。
玩家是否继续进去？

如果确认，还是继续进去；
如果取消，则退出。

**Comment by Kinderzhang** [comment]
文案key: The concept, the number of awards and had to deplete.

**Comment by aoxu** [comment]
真机已验证，只需要把2.YOU WILL GET NO REWARDS.的key删除就可以了。
